/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PostTest5;

import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author acer
 */
public class Pelanggan_bee extends javax.swing.JFrame {
public String ckelamin;
private DefaultTableModel model;


public void InitTable(){
    model = new DefaultTableModel();
    model.addColumn("Nama");
    model.addColumn("No.Telepon");
    model.addColumn("Kota Asal");
    model.addColumn("Jenis kelamin");
    model.addColumn("Pekerjaan");
    data.setModel(model);
}
    /**
     * Creates new form Pelanggan_bee
     */
    public Pelanggan_bee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        nope = new javax.swing.JTextField();
        kota = new javax.swing.JComboBox<String>();
        hps = new javax.swing.JButton();
        smpn = new javax.swing.JButton();
        tmbh = new javax.swing.JButton();
        updt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cowok = new javax.swing.JRadioButton();
        cewek = new javax.swing.JRadioButton();
        pekerjaan = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();
        cloese = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 2, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Tabel Pelanggan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        jLabel1.setText("Nama");

        jLabel2.setText("No. Telepon");

        jLabel3.setText("Kota Asal");

        kota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Samarinda", "Tenggarong", "Melak", "Kota Bangun", "Bontang", "Penajam" }));

        hps.setBackground(new java.awt.Color(0, 153, 102));
        hps.setText("Hapus");
        hps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpsActionPerformed(evt);
            }
        });

        smpn.setBackground(new java.awt.Color(255, 255, 102));
        smpn.setText("Simpan");
        smpn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smpnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                smpnMouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                smpnMouseReleased(evt);
            }
        });
        smpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smpnActionPerformed(evt);
            }
        });

        tmbh.setBackground(new java.awt.Color(0, 255, 51));
        tmbh.setText("Tambah");
        tmbh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmbhMouseClicked(evt);
            }
        });
        tmbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbhActionPerformed(evt);
            }
        });

        updt.setBackground(new java.awt.Color(204, 204, 0));
        updt.setText("Update");
        updt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis Kelamin");

        buttonGroup1.add(cowok);
        cowok.setText("Laki-laki");

        buttonGroup1.add(cewek);
        cewek.setText("Perempuan");

        pekerjaan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PNS", "WIRASWATA", "BURUH", "TANI", "NELAYAN" }));

        jLabel6.setText("Pekerjaan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(kota, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pekerjaan, javax.swing.GroupLayout.Alignment.LEADING, 0, 239, Short.MAX_VALUE))
                    .addComponent(nope, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(nm)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cowok, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(cewek)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smpn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tmbh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(updt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hps, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tmbh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(smpn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kota, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cowok)
                            .addComponent(jLabel5)
                            .addComponent(cewek))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hps, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        data.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "No. Telepon", "Kota Asal", "Pekerjaan", "Jenis Kelamin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        data.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataFocusLost(evt);
            }
        });
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data);

        cloese.setBackground(new java.awt.Color(255, 0, 0));
        cloese.setForeground(new java.awt.Color(0, 51, 204));
        cloese.setText("Keluar");
        cloese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cloeseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cloese))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cloese)
                .addGap(99, 99, 99))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smpnActionPerformed
        Object[] data = new Object[5];
        data[0] = nm.getText();
        data[1] = nope.getText();
        data[2] = kota.getSelectedItem().toString();
        data[3] = pekerjaan.getSelectedItem().toString();
        if(cowok.isSelected()==true){
            data[4]="laki-laki";
            ckelamin = "LK";
        }
        if(cewek.isSelected()==true){
            data[4]="Perempuan";
            ckelamin = "PRMN";
        }
        model.addRow(data); 
    
    }//GEN-LAST:event_smpnActionPerformed

    private void tmbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbhActionPerformed
        // TODO add your handling code here:
        nm.setEnabled(true);
        nope.setEnabled(true);
        kota.setEnabled(true);
        pekerjaan.setEnabled(true);
        tmbh.setEnabled(false);
        updt.setEnabled(false);
        hps.setEnabled(false);
        smpn.setEnabled(false);
        cowok.setEnabled(true);
        cewek.setEnabled(true);
    }//GEN-LAST:event_tmbhActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        InitTable();
    }//GEN-LAST:event_formComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        nm.setEnabled(false);
        nope.setEnabled(false);
        kota.setEnabled(false);
        pekerjaan.setEnabled(false);
        tmbh.setEnabled(true);
        updt.setEnabled(false);
        hps.setEnabled(false);
        smpn.setEnabled(false);
        buttonGroup1.clearSelection();
        cowok.setEnabled(false);
        cewek.setEnabled(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void smpnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smpnMouseClicked
        nm.setEnabled(false);
        nope.setEnabled(false);
        kota.setEnabled(false);
        pekerjaan.setEnabled(false);
        tmbh.setEnabled(true);
        updt.setEnabled(true);
        hps.setEnabled(true);
        smpn.setEnabled(false);
        cowok.setEnabled(false);
        cewek.setEnabled(false);
        cek();
    }//GEN-LAST:event_smpnMouseClicked
public void hapus (){
        nm.setText("");
        nope.setText("");
}
    public void cek() {
    if (nm.getText().length()==0 ||
        nope.getText().length()==0 ||
        kota.getSelectedItem()==null ||
        buttonGroup1.getSelection()==null ||
        pekerjaan.getSelectedItem()==null){
smpn.setEnabled(false);
     }
     else {
        smpn.setEnabled(true);
         
}
}
    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
cek();

    }//GEN-LAST:event_jPanel3MouseEntered

    private void smpnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smpnMouseEntered

    }//GEN-LAST:event_smpnMouseEntered

    private void smpnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smpnMouseReleased
hapus();
    }//GEN-LAST:event_smpnMouseReleased

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
        int baris = data.getSelectedRow();
        String up_nama = data.getValueAt(baris, 0).toString();
        String up_nope = data.getValueAt(baris, 1).toString();
        String up_kota = data.getValueAt(baris, 2).toString();
        String up_pekerjaan = data.getValueAt(baris, 3).toString();
        String up_jeniskelamin = data.getValueAt(baris, 4).toString();
        
        nm.setText(up_nama);
        nope.setText(up_nope);
        kota.setSelectedItem(up_nama);
        pekerjaan.setSelectedItem(up_pekerjaan);
        
        nm.setEnabled(true);
        nope.setEnabled(true);
        kota.setEnabled(true);
        pekerjaan.setEnabled(true);
        cowok.setEnabled(true);
        cewek.setEnabled(true);
    }//GEN-LAST:event_dataMouseClicked

    private void hpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpsActionPerformed
    try{
        int i =  data.getSelectedRow();
        model.removeRow(i);
        hapus(); 
    }catch (ArrayIndexOutOfBoundsException e) {JOptionPane.showMessageDialog(this,"Anda Belum Memilih Data untuk di update!!!"); return;}
    
    }//GEN-LAST:event_hpsActionPerformed

    private void updtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtActionPerformed
try {
        int baris = data.getSelectedRow();
        data.setValueAt(nm.getText(), baris, 0);
        data.setValueAt(nope.getText(), baris, 1);
        data.setValueAt(kota.getSelectedItem(), baris, 2);
        data.setValueAt(pekerjaan.getSelectedItem(), baris, 3);
if (ckelamin.equals("LK") && cowok.isSelected()==true) {
     data.setValueAt("laki-laki", baris, 4);
} 
else if (ckelamin.equals("LK") && cewek.isSelected()==true){ 
     data.setValueAt("Perempuan", baris, 4);
}
else if (ckelamin.equals("PRMN") && cowok.isSelected()==true){ 
     data.setValueAt("laki-laki", baris, 4);
}
else if (ckelamin.equals("PRMN") && cewek.isSelected()==true){ 
     data.setValueAt("Perempuan", baris, 4);
}
}catch (ArrayIndexOutOfBoundsException e) {JOptionPane.showMessageDialog(this,"Anda Belum Memilih Data untuk dihapuss!!!"); return;}
    data.clearSelection();
    }//GEN-LAST:event_updtActionPerformed

    private void tmbhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmbhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tmbhMouseClicked

    private void dataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dataFocusLost
    }//GEN-LAST:event_dataFocusLost

    private void cloeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cloeseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cloeseActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan_bee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan_bee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan_bee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan_bee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelanggan_bee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cewek;
    private javax.swing.JButton cloese;
    private javax.swing.JRadioButton cowok;
    private javax.swing.JTable data;
    private javax.swing.JButton hps;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kota;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField nope;
    private javax.swing.JComboBox<String> pekerjaan;
    private javax.swing.JButton smpn;
    private javax.swing.JButton tmbh;
    private javax.swing.JButton updt;
    // End of variables declaration//GEN-END:variables
}
